# -*- coding: utf-8 -*-
"""logAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p8ONgj9V8FhPH0AdlX5JToDpKyzyIxAl
"""

################################################################################
# ANALISI COMPLETA DATASET MUTINY - KUBERNETES LOG PARSING
# Confronto Manual Keyword-Based vs Drain Structure-Based Detection
# Con e Senza Preprocessing
################################################################################

# ============================
# SEZIONE 1: IMPORT E SETUP
# ============================
!pip install drain3

import os
import random
import re
import time
import gc
from collections import defaultdict, Counter
import json
import pickle

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from drain3 import TemplateMiner
from drain3.file_persistence import FilePersistence
from drain3.template_miner_config import TemplateMinerConfig

from sklearn.metrics import cohen_kappa_score
from statsmodels.stats.contingency_tables import mcnemar

# Configurazione grafici (publication-ready)
plt.rcParams['figure.dpi'] = 100
plt.rcParams['font.size'] = 13
plt.rcParams['axes.labelsize'] = 13
plt.rcParams['axes.titlesize'] = 14
plt.rcParams['legend.fontsize'] = 11
plt.rcParams['figure.figsize'] = (10, 6)

print("="*80)
print("SCRIPT INIZIALIZZATO CORRETTAMENTE")
print("="*80)

# ============================
# SEZIONE 2: CONFIGURAZIONE
# ============================

# --- Parametri Dataset ---
BASE_DIR = "/content/drive/MyDrive/Mutiny_dataset 2"
CATEGORIES = ["baseline", "less_resources", "more_resources", "network"]
USE_FULL_DATASET = True # True = intero dataset (~2800 file), False = subset test
TEST_SUBSET_SIZE = 50  # File per categoria se USE_FULL_DATASET=False
SEED = 42
random.seed(SEED)
np.random.seed(SEED)

# --- Parametri Manual Detection ---
KEYWORDS = ["error", "fail", "failed", "exception", "timeout",
            "panic", "crash", "unavailable", "refused"]
MIN_MANUAL_HITS = 8           # Minimo numero assoluto di keyword per detection
MIN_MANUAL_PCT = 0.003        # Minima percentuale keyword sul totale righe (0.3%)

# --- Parametri Drain ---
DRAIN_SIM_TH = 0.6            # Soglia similarità (0.5-0.7 consigliato)
DRAIN_DEPTH = 4               # Profondità albero Drain
CLUSTER_KEYWORD_PCT = 0.03    # Percentuale minima keyword in cluster (3%)
MIN_CLUSTER_SIZE = 5          # Dimensione minima cluster
MAX_CLUSTER_SIZE_RATIO = 0.08 # Max 8% del totale righe per singolo cluster

# --- Checkpoint ---
CHECKPOINT_ENABLED = True
CHECKPOINT_INTERVAL = 500     # Salva checkpoint ogni N file
CHECKPOINT_DIR = "/content/checkpoints"

print(f"\n{'='*80}")
print("CONFIGURAZIONE PARAMETRI")
print(f"{'='*80}")
print(f"Dataset: {'COMPLETO' if USE_FULL_DATASET else f'SUBSET ({TEST_SUBSET_SIZE} file/categoria)'}")
print(f"Seed riproducibilità: {SEED}")
print(f"Manual detection: MIN_HITS={MIN_MANUAL_HITS}, MIN_PCT={MIN_MANUAL_PCT}")
print(f"Drain: sim_th={DRAIN_SIM_TH}, depth={DRAIN_DEPTH}")
print(f"Cluster filtering: MIN_SIZE={MIN_CLUSTER_SIZE}, MAX_RATIO={MAX_CLUSTER_SIZE_RATIO}, KEYWORD_PCT={CLUSTER_KEYWORD_PCT}")
print(f"Checkpoint: {'ABILITATI' if CHECKPOINT_ENABLED else 'DISABILITATI'} (ogni {CHECKPOINT_INTERVAL} file)")
print(f"{'='*80}\n")

# ============================
# SEZIONE 3: FUNZIONI UTILITY
# ============================

def preprocess_k8s_log(log_line):
    """
    Applica preprocessing a una riga di log Kubernetes.
    Normalizza timestamp, IP, UUID, hash e identificatori variabili,
    mantenendo la semantica del messaggio di errore.

    Args:
        log_line (str): Riga log originale

    Returns:
        str: Riga log preprocessata

    Riferimento: Metodologia preprocessing standard per log strutturati
    """
    if not log_line or not log_line.strip():
        return ""

    content = log_line.strip()

    # Normalizzazione timestamp (formati ISO8601 e varianti)
    content = re.sub(r'^\d{4}-\d{2}-\d{2}[Tt]\d{2}:\d{2}:\d{2}\.\d+([+-]\d{2}:\d{2}|[Zz])?', '<timestamp>', content)
    content = re.sub(r'^\d{4}-\d{2}-\d{2}[Tt]\d{2}:\d{2}:\d{2}([+-]\d{2}:\d{2}|[Zz])?', '<timestamp>', content)
    content = re.sub(r't=\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}\.\d+', 't=<timestamp>', content, flags=re.IGNORECASE)
    content = re.sub(r'\d{4}-\d{2}-\d{2}[Tt]\d{2}:\d{2}:\d{2}\.\d+[Zz]?', '<timestamp>', content, flags=re.IGNORECASE)
    content = re.sub(r'\b\d{4}-\d{2}-\d{2}\b', '<date>', content)
    content = re.sub(r'\b[iI]\d{4}\b', '<idate>', content)

    # Normalizzazione indirizzi IP e porte
    content = re.sub(r'\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}(:\d+)?\b', '<ip_addr>', content)
    content = re.sub(r'\[::1\](:\d+)?', '<ip_addr>', content)
    content = re.sub(r'https?://[^\s/$.?#].[^\s]*', 'https://<ip_addr>', content, flags=re.IGNORECASE)

    # Normalizzazione UUID
    content = re.sub(r'\b[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}\b', '<uuid>', content, flags=re.IGNORECASE)

    # Normalizzazione hash e identificatori lunghi
    content = re.sub(r'\b[a-f0-9]{32,}\b', '<hash>', content, flags=re.IGNORECASE)
    content = re.sub(r'\b[a-f0-9]{16,31}\b', '<hash>', content, flags=re.IGNORECASE)

    # Normalizzazione identificatori Pod, ReplicaSet
    content = re.sub(r'\b([a-zA-Z][a-zA-Z0-9-]*)-[a-f0-9]{5,}(-[a-z0-9]+)?\b', r'\1-<pod_id>', content, flags=re.IGNORECASE)
    content = re.sub(r'\b([a-zA-Z][a-zA-Z0-9-]*)-[a-f0-9]{8,10}\b', r'\1-<rs_id>', content, flags=re.IGNORECASE)

    # Normalizzazione audit ID, UID, resource version
    content = re.sub(r'audit-ID="[^"]*"', 'audit-ID="<audit_id>"', content, flags=re.IGNORECASE)
    content = re.sub(r'uid="[^"]*"', 'uid="<uuid>"', content, flags=re.IGNORECASE)
    content = re.sub(r'resource[vV]ersion[=:]["?\d+"?]?', 'resourceVersion="<res_ver>"', content, flags=re.IGNORECASE)
    content = re.sub(r'node[=:"][^"]*"?', 'node="<node_name>"', content, flags=re.IGNORECASE)

    # Normalizzazione numeri grandi
    content = re.sub(r'\b\d{10,}\b(?![.%])', '<large_num>', content)
    content = re.sub(r'\b\d{8,9}\b(?![.%ms])', '<num_id>', content)

    # Rimozione spazi multipli
    return re.sub(r'\s+', ' ', content).strip()


def collect_all_log_files(base_dir, categories):
    """
    Raccoglie tutti i file di log dal dataset Mutiny.
    Segue la struttura: categoria/scenario/componente/*.log

    Args:
        base_dir (str): Directory radice dataset Mutiny
        categories (list): Lista categorie da processare

    Returns:
        list: Lista path assoluti file log
    """
    all_files = []

    for cat in categories:
        cat_dir = os.path.join(base_dir, cat)
        if not os.path.isdir(cat_dir):
            print(f"[WARNING] Categoria {cat} non trovata in {cat_dir}")
            continue

        # Esplora ricorsivamente tutti i file .log
        for root, dirs, files in os.walk(cat_dir):
            for file in files:
                if file.endswith(".log"):
                    all_files.append(os.path.join(root, file))

    return all_files


def collect_balanced_subset(base_dir, categories, files_per_category):
    """
    Raccoglie subset bilanciato per testing rapido.
    Seleziona N file casuali per categoria.

    Args:
        base_dir (str): Directory radice dataset
        categories (list): Lista categorie
        files_per_category (int): File da selezionare per categoria

    Returns:
        list: Lista path file selezionati
    """
    selected = []

    for cat in categories:
        cat_dir = os.path.join(base_dir, cat)
        if not os.path.isdir(cat_dir):
            continue

        cat_files = []
        for root, dirs, files in os.walk(cat_dir):
            for file in files:
                if file.endswith(".log"):
                    cat_files.append(os.path.join(root, file))

        # Campiona casualmente
        sample_size = min(files_per_category, len(cat_files))
        selected.extend(random.sample(cat_files, sample_size))

    return selected


def manual_detect_rule(matches, total_lines):
    """
    Applica regola di detection manuale keyword-based.
    Un file è considerato anomalo se:
    - Contiene almeno MIN_MANUAL_HITS keyword, OPPURE
    - La percentuale di righe con keyword supera MIN_MANUAL_PCT

    Args:
        matches (int): Numero righe contenenti keyword
        total_lines (int): Numero totale righe file

    Returns:
        bool: True se file rilevato come anomalo
    """
    if matches >= MIN_MANUAL_HITS:
        return True
    if total_lines > 0 and (matches / total_lines) >= MIN_MANUAL_PCT:
        return True
    return False


def compute_binary_metrics(y_true, y_pred):
    """
    Calcola metriche binarie di classificazione.

    Args:
        y_true (array-like): Label ground truth (0=normale, 1=fault)
        y_pred (array-like): Label predette

    Returns:
        dict: Dizionario con tp, fp, fn, tn, precision, recall, f1
    """
    tp = int(((y_true == 1) & (y_pred == 1)).sum())
    fp = int(((y_true == 0) & (y_pred == 1)).sum())
    fn = int(((y_true == 1) & (y_pred == 0)).sum())
    tn = int(((y_true == 0) & (y_pred == 0)).sum())

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0

    return {
        "tp": tp, "fp": fp, "fn": fn, "tn": tn,
        "precision": precision, "recall": recall, "f1": f1
    }


def save_checkpoint(data, checkpoint_name):
    """Salva checkpoint intermedio."""
    if not CHECKPOINT_ENABLED:
        return

    os.makedirs(CHECKPOINT_DIR, exist_ok=True)
    checkpoint_path = os.path.join(CHECKPOINT_DIR, f"{checkpoint_name}.pkl")

    with open(checkpoint_path, 'wb') as f:
        pickle.dump(data, f)

    print(f"  [CHECKPOINT] Salvato: {checkpoint_path}")


def load_checkpoint(checkpoint_name):
    """Carica checkpoint se esistente."""
    if not CHECKPOINT_ENABLED:
        return None

    checkpoint_path = os.path.join(CHECKPOINT_DIR, f"{checkpoint_name}.pkl")

    if os.path.exists(checkpoint_path):
        with open(checkpoint_path, 'rb') as f:
            return pickle.load(f)

    return None


# ============================
# SEZIONE 4: FUNZIONE PRINCIPALE ANALISI
# ============================

def run_mode(mode, subset_files, keywords):
    """
    Esegue parsing e detection per modalità specificata (raw o preproc).

    Implementa:
    1. Parsing riga per riga con/senza preprocessing
    2. Detection manuale keyword-based
    3. Clustering Drain con identificazione cluster sospetti
    4. Salvataggio checkpoint automatici

    Args:
        mode (str): "raw" o "preproc"
        subset_files (list): Lista path file da analizzare
        keywords (list): Lista keyword per manual detection

    Returns:
        tuple: (df_results, cluster_info, miner, cluster_total)
            - df_results: DataFrame con risultati per file
            - cluster_info: Dict con info cluster Drain
            - miner: Oggetto TemplateMiner addestrato
            - cluster_total: Counter righe per cluster

    Riferimenti:
        - He et al. (2017): Algoritmo Drain
        - Drain3: Implementazione con persistenza
    """

    print(f"\n{'='*80}")
    print(f"MODALITÀ: {mode.upper()}")
    print(f"{'='*80}")

    # Verifica checkpoint esistente
    checkpoint_data = load_checkpoint(f"run_{mode}")
    if checkpoint_data is not None:
        print(f"[INFO] Checkpoint trovato per modalità {mode}. Ripresa da ultimo salvataggio.")
        return checkpoint_data

    # Configurazione Drain
    config = TemplateMinerConfig()
    config.profiling_enabled = False
    config.drain_sim_th = DRAIN_SIM_TH
    config.drain_depth = DRAIN_DEPTH
    config.max_children = 100

    persistence = FilePersistence(f"drain_state_{mode}_{int(time.time())}.json")
    miner = TemplateMiner(persistence, config)

    # Contatori
    cluster_total = Counter()      # Righe totali per cluster
    cluster_keyword = Counter()    # Righe con keyword per cluster
    records = []                   # Risultati per file

    print(f"\n[{mode.upper()}] Inizio processing di {len(subset_files)} file...")
    start_time = time.time()
    processed = 0

    for file_idx, file_path in enumerate(subset_files):
        file_path = file_path.strip()

        if not os.path.exists(file_path):
            print(f"[WARN] File non trovato: {file_path}")
            continue

        # Contatori per file corrente
        file_lines = 0
        file_manual_matches = 0
        file_cluster_ids = set()

        # Processing riga per riga
        try:
            with open(file_path, "r", errors="ignore") as fh:
                for line in fh:
                    file_lines += 1

                    # Applica preprocessing se richiesto
                    if mode == "preproc":
                        proc = preprocess_k8s_log(line)
                    else:
                        proc = line.strip()

                    if not proc:
                        continue

                    # Manual detection: conta keyword
                    low = proc.lower()
                    if any(k in low for k in keywords):
                        file_manual_matches += 1

                    # Drain clustering
                    result = miner.add_log_message(proc)
                    cid = result.get("cluster_id", None)

                    if cid is not None:
                        file_cluster_ids.add(cid)
                        cluster_total[cid] += 1
                        if any(k in low for k in keywords):
                            cluster_keyword[cid] += 1

        except Exception as e:
            print(f"[ERROR] Errore processing file {file_path}: {e}")
            continue

        # Determina detection manuale
        manual_detected = manual_detect_rule(file_manual_matches, file_lines)

        # Estrai metadati file (categoria, componente)
        cat = next((c for c in CATEGORIES if f"/{c}/" in file_path or f"\\{c}\\" in file_path), "unknown")

        if "kube-apiserver" in file_path:
            comp = "kube-apiserver"
        elif "kube-scheduler" in file_path:
            comp = "kube-scheduler"
        elif "kube-controller-manager" in file_path:
            comp = "kube-controller-manager"
        else:
            comp = "unknown"

        # Salva record
        records.append({
            "file": file_path,
            "category": cat,
            "component": comp,
            "mode": mode,
            "total_lines": file_lines,
            "manual_matches": file_manual_matches,
            "manual_detected": manual_detected,
            "cluster_ids": file_cluster_ids
        })

        processed += 1

        # Progress + Checkpoint
        if processed % 50 == 0:
            elapsed = time.time() - start_time
            avg_time = elapsed / processed
            remaining = (len(subset_files) - processed) * avg_time
            print(f"  Progress: {processed}/{len(subset_files)} files | "
                  f"Elapsed: {elapsed/60:.1f}min | ETA: {remaining/60:.1f}min")

        if CHECKPOINT_ENABLED and processed % CHECKPOINT_INTERVAL == 0:
            partial_data = (records, cluster_total, cluster_keyword, miner)
            save_checkpoint(partial_data, f"run_{mode}_partial_{processed}")
            gc.collect()  # Garbage collection

    # Statistiche clustering
    total_lines_processed = sum(cluster_total.values())
    print(f"\n[{mode.upper()}] Processing completato:")
    print(f"  - File analizzati: {processed}")
    print(f"  - Righe totali: {total_lines_processed:,}")
    print(f"  - Cluster generati: {len(cluster_total)}")
    print(f"  - Tempo totale: {(time.time()-start_time)/60:.1f} minuti")

    # Identificazione cluster sospetti
    suspicious_clusters = set()

    for cid, tot in cluster_total.items():
        kcount = cluster_keyword.get(cid, 0)

        # Filtro 1: dimensione minima
        if tot < MIN_CLUSTER_SIZE:
            continue

        # Filtro 2: esclude cluster troppo grandi (pattern generici)
        if total_lines_processed > 0 and (tot / total_lines_processed) > MAX_CLUSTER_SIZE_RATIO:
            continue

        # Filtro 3: percentuale keyword
        if tot > 0 and (kcount / tot) >= CLUSTER_KEYWORD_PCT:
            suspicious_clusters.add(cid)

    print(f"  - Cluster sospetti identificati: {len(suspicious_clusters)}")

    # Aggiungi info Drain ai record
    for rec in records:
        cids = rec["cluster_ids"]
        rec["drain_num_clusters_seen"] = len(cids)
        rec["drain_num_suspicious_clusters_seen"] = len([c for c in cids if c in suspicious_clusters])
        rec["drain_detected"] = rec["drain_num_suspicious_clusters_seen"] > 0

    # Crea info cluster per analisi
    cluster_info = {}
    for cluster in miner.drain.clusters:
        cluster_info[cluster.cluster_id] = {
            "cluster_id": cluster.cluster_id,
            "size": cluster.size,
            "template": cluster.get_template(),
            "keyword_count": int(cluster_keyword.get(cluster.cluster_id, 0)),
            "is_suspicious": (cluster.cluster_id in suspicious_clusters)
        }

    # Converti in DataFrame
    df = pd.DataFrame(records)

    # Salva checkpoint finale
    final_data = (df, cluster_info, miner, cluster_total)
    save_checkpoint(final_data, f"run_{mode}")

    return df, cluster_info, miner, cluster_total


# ===============================================
# SEZIONE 5: CARICAMENTO DATASET
# ===============================================

print(f"\n{'='*80}")
print("CARICAMENTO DATASET")
print(f"{'='*80}")

if USE_FULL_DATASET:
    print("[INFO] Modalità: DATASET COMPLETO")
    all_files = collect_all_log_files(BASE_DIR, CATEGORIES)
else:
    print(f"[INFO] Modalità: SUBSET TEST ({TEST_SUBSET_SIZE} file/categoria)")
    all_files = collect_balanced_subset(BASE_DIR, CATEGORIES, TEST_SUBSET_SIZE)

print(f"\n✓ Totale file selezionati: {len(all_files)}")

# Statistiche distribuzione
for cat in CATEGORIES:
    count = sum(1 for f in all_files if f"/{cat}/" in f or f"\\{cat}\\" in f)
    print(f"  - {cat:20s}: {count:4d} file ({100*count/len(all_files):.1f}%)")

# ===============================================
# SEZIONE 6: ESECUZIONE ANALISI RAW
# ===============================================

print(f"\n{'='*80}")
print("FASE 1: ANALISI MODALITÀ RAW (log originali)")
print(f"{'='*80}")

t0_raw = time.time()
df_raw, clusters_raw, miner_raw, cluster_total_raw = run_mode("raw", all_files, KEYWORDS)
elapsed_raw = time.time() - t0_raw

print(f"\n✓ Modalità RAW completata in {elapsed_raw/60:.1f} minuti ({elapsed_raw/len(all_files):.2f}s/file)")

# ===============================================
# SEZIONE 7: ESECUZIONE ANALISI PREPROC
# ===============================================

print(f"\n{'='*80}")
print("FASE 2: ANALISI MODALITÀ PREPROC (log normalizzati)")
print(f"{'='*80}")

t0_pre = time.time()
df_pre, clusters_pre, miner_pre, cluster_total_pre = run_mode("preproc", all_files, KEYWORDS)
elapsed_pre = time.time() - t0_pre

print(f"\n✓ Modalità PREPROC completata in {elapsed_pre/60:.1f} minuti ({elapsed_pre/len(all_files):.2f}s/file)")

# ===============================================
# SEZIONE 8: CALCOLO METRICHE
# ===============================================

print(f"\n{'='*80}")
print("CALCOLO METRICHE COMPARATIVE")
print(f"{'='*80}")

# Aggiungi label ground truth (fault injection = categorie LeR, MoR, Net)
df_raw["is_fault_injection"] = df_raw["category"].apply(lambda x: x in ["less_resources", "more_resources", "network"])
df_pre["is_fault_injection"] = df_pre["category"].apply(lambda x: x in ["less_resources", "more_resources", "network"])

# Metriche RAW
fault_mask_raw = df_raw["is_fault_injection"] == True
manual_raw_metrics = compute_binary_metrics(
    df_raw.loc[fault_mask_raw, "is_fault_injection"].astype(int),
    df_raw.loc[fault_mask_raw, "manual_detected"].astype(int)
)
drain_raw_metrics = compute_binary_metrics(
    df_raw.loc[fault_mask_raw, "is_fault_injection"].astype(int),
    df_raw.loc[fault_mask_raw, "drain_detected"].astype(int)
)

# Metriche PREPROC
fault_mask_pre = df_pre["is_fault_injection"] == True
manual_pre_metrics = compute_binary_metrics(
    df_pre.loc[fault_mask_pre, "is_fault_injection"].astype(int),
    df_pre.loc[fault_mask_pre, "manual_detected"].astype(int)
)
drain_pre_metrics = compute_binary_metrics(
    df_pre.loc[fault_mask_pre, "is_fault_injection"].astype(int),
    df_pre.loc[fault_mask_pre, "drain_detected"].astype(int)
)

# ===============================================
# SEZIONE 9: OUTPUT RISULTATI FORMATTATI
# ===============================================

print(f"\n{'='*80}")
print("RISULTATI GLOBALI - CONFRONTO MANUAL vs DRAIN")
print(f"{'='*80}")

print(f"\n{'Metodo':<25} | {'Precision':>10} | {'Recall':>10} | {'F1-Score':>10}")
print("-"*80)
print(f"{'Manual (RAW)':<25} | {manual_raw_metrics['precision']:>10.3f} | {manual_raw_metrics['recall']:>10.3f} | {manual_raw_metrics['f1']:>10.3f}")
print(f"{'Manual (PREPROC)':<25} | {manual_pre_metrics['precision']:>10.3f} | {manual_pre_metrics['recall']:>10.3f} | {manual_pre_metrics['f1']:>10.3f}")
print(f"{'Δ Manual (R-P)':<25} | {manual_raw_metrics['precision']-manual_pre_metrics['precision']:>+10.3f} | {manual_raw_metrics['recall']-manual_pre_metrics['recall']:>+10.3f} | {manual_raw_metrics['f1']-manual_pre_metrics['f1']:>+10.3f}")
print("-"*80)
print(f"{'Drain (RAW)':<25} | {drain_raw_metrics['precision']:>10.3f} | {drain_raw_metrics['recall']:>10.3f} | {drain_raw_metrics['f1']:>10.3f}")
print(f"{'Drain (PREPROC)':<25} | {drain_pre_metrics['precision']:>10.3f} | {drain_pre_metrics['recall']:>10.3f} | {drain_pre_metrics['f1']:>10.3f}")
print(f"{'Δ Drain (R-P)':<25} | {drain_raw_metrics['precision']-drain_pre_metrics['precision']:>+10.3f} | {drain_raw_metrics['recall']-drain_pre_metrics['recall']:>+10.3f} | {drain_raw_metrics['f1']-drain_pre_metrics['f1']:>+10.3f}")
print("="*80)

# Detection rate per categoria
print(f"\n{'='*80}")
print("DETECTION RATE PER CATEGORIA")
print(f"{'='*80}")

for cat in CATEGORIES:
    mask_raw = df_raw["category"] == cat
    mask_pre = df_pre["category"] == cat
    n_files = mask_raw.sum()

    manual_raw_rate = df_raw.loc[mask_raw, "manual_detected"].mean()
    manual_pre_rate = df_pre.loc[mask_pre, "manual_detected"].mean()
    drain_raw_rate = df_raw.loc[mask_raw, "drain_detected"].mean()
    drain_pre_rate = df_pre.loc[mask_pre, "drain_detected"].mean()

    print(f"\n{cat} ({n_files} file):")
    print(f"  Manual: {manual_pre_rate:5.1%} (preproc) vs {manual_raw_rate:5.1%} (raw) → Δ={manual_raw_rate-manual_pre_rate:+5.1%}")
    print(f"  Drain:  {drain_pre_rate:5.1%} (preproc) vs {drain_raw_rate:5.1%} (raw) → Δ={drain_raw_rate-drain_pre_rate:+5.1%}")

# Performance per componente
print(f"\n{'='*80}")
print("PERFORMANCE PER COMPONENTE (solo fault injection)")
print(f"{'='*80}")

for comp in ["kube-apiserver", "kube-scheduler", "kube-controller-manager"]:
    mask_raw = (df_raw["component"] == comp) & (df_raw["is_fault_injection"] == True)
    mask_pre = (df_pre["component"] == comp) & (df_pre["is_fault_injection"] == True)
    n_files = mask_raw.sum()

    if n_files < 5:
        print(f"\n{comp}: skipped (solo {n_files} file)")
        continue

    # Manual
    manual_raw_comp = compute_binary_metrics(
        df_raw.loc[mask_raw, "is_fault_injection"].astype(int),
        df_raw.loc[mask_raw, "manual_detected"].astype(int)
    )
    manual_pre_comp = compute_binary_metrics(
        df_pre.loc[mask_pre, "is_fault_injection"].astype(int),
        df_pre.loc[mask_pre, "manual_detected"].astype(int)
    )

    # Drain
    drain_raw_comp = compute_binary_metrics(
        df_raw.loc[mask_raw, "is_fault_injection"].astype(int),
        df_raw.loc[mask_raw, "drain_detected"].astype(int)
    )
    drain_pre_comp = compute_binary_metrics(
        df_pre.loc[mask_pre, "is_fault_injection"].astype(int),
        df_pre.loc[mask_pre, "drain_detected"].astype(int)
    )

    print(f"\n{comp} ({n_files} file):")
    print(f"  Manual (RAW):    P={manual_raw_comp['precision']:.3f}, R={manual_raw_comp['recall']:.3f}, F1={manual_raw_comp['f1']:.3f}")
    print(f"  Manual (PREPROC): P={manual_pre_comp['precision']:.3f}, R={manual_pre_comp['recall']:.3f}, F1={manual_pre_comp['f1']:.3f}")
    print(f"  Drain (RAW):     P={drain_raw_comp['precision']:.3f}, R={drain_raw_comp['recall']:.3f}, F1={drain_raw_comp['f1']:.3f}")
    print(f"  Drain (PREPROC):  P={drain_pre_comp['precision']:.3f}, R={drain_pre_comp['recall']:.3f}, F1={drain_pre_comp['f1']:.3f}")

# Cluster statistics
print(f"\n{'='*80}")
print("CLUSTER GENERATION: RAW vs PREPROC")
print(f"{'='*80}")

total_clusters_raw = len(clusters_raw)
total_clusters_pre = len(clusters_pre)
susp_raw = sum(1 for info in clusters_raw.values() if info["is_suspicious"])
susp_pre = sum(1 for info in clusters_pre.values() if info["is_suspicious"])

print(f"\nCluster totali generati:")
print(f"  RAW:     {total_clusters_raw:4d} cluster ({susp_raw:3d} sospetti)")
print(f"  PREPROC: {total_clusters_pre:4d} cluster ({susp_pre:3d} sospetti)")
print(f"  Δ:       {total_clusters_raw-total_clusters_pre:+4d} cluster ({susp_raw-susp_pre:+3d} sospetti)")

lines_per_cluster_raw = sum(cluster_total_raw.values()) / total_clusters_raw if total_clusters_raw > 0 else 0
lines_per_cluster_pre = sum(cluster_total_pre.values()) / total_clusters_pre if total_clusters_pre > 0 else 0

print(f"\nEfficienza clustering (righe/cluster):")
print(f"  RAW:     {lines_per_cluster_raw:,.1f} righe/cluster")
print(f"  PREPROC: {lines_per_cluster_pre:,.1f} righe/cluster")

# Test statistici
print(f"\n{'='*80}")
print("TEST STATISTICI")
print(f"{'='*80}")

# McNemar: Manual vs Drain (PREPROC)
a = int(((df_pre["manual_detected"]) & (df_pre["drain_detected"])).sum())
b = int(((df_pre["manual_detected"]) & (~df_pre["drain_detected"])).sum())
c = int((~(df_pre["manual_detected"]) & (df_pre["drain_detected"])).sum())
d = int((~(df_pre["manual_detected"]) & (~df_pre["drain_detected"])).sum())
table_pre = [[a, b], [c, d]]

print(f"\n1. McNemar Test: Manual vs Drain (PREPROC)")
print(f"   Tabella contingenza: [[{a},{b}],[{c},{d}]]")

try:
    mres = mcnemar(table_pre, exact=False, correction=True)
    print(f"   Statistic: {mres.statistic:.3f}, p-value: {mres.pvalue:.4f}")
    if mres.pvalue < 0.05:
        print(f"   → Differenza SIGNIFICATIVA (p<0.05)")
    else:
        print(f"   → Differenza NON significativa (p≥0.05)")
except Exception as e:
    print(f"   Error: {e}")

# Cohen's Kappa: agreement su baseline
baseline_mask = df_pre["category"] == "baseline"
if baseline_mask.sum() > 0:
    try:
        kappa = cohen_kappa_score(
            df_pre.loc[baseline_mask, "manual_detected"].astype(int),
            df_pre.loc[baseline_mask, "drain_detected"].astype(int)
        )
        print(f"\n2. Cohen's Kappa: Manual vs Drain su BASELINE (PREPROC)")
        print(f"   Kappa: {kappa:.3f}")
        if kappa > 0.8:
            print(f"   → Accordo QUASI PERFETTO")
        elif kappa > 0.6:
            print(f"   → Accordo SOSTANZIALE")
        elif kappa > 0.4:
            print(f"   → Accordo MODERATO")
        else:
            print(f"   → Accordo DEBOLE")
    except Exception as e:
        print(f"   Error: {e}")

# ===============================================
# SEZIONE 10: VISUALIZZAZIONI
# ===============================================

print(f"\n{'='*80}")
print("GENERAZIONE GRAFICI")
print(f"{'='*80}")

# Grafico 1: Detection Rate per Categoria (4 metodi)
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle('Detection Rate per Categoria', fontsize=16, fontweight='bold')

methods = ['Manual (PREPROC)', 'Manual (RAW)', 'Drain (PREPROC)', 'Drain (RAW)']
colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728']

for idx, cat in enumerate(CATEGORIES):
    ax = axes[idx // 2, idx % 2]

    mask_raw = df_raw["category"] == cat
    mask_pre = df_pre["category"] == cat

    rates = [
        df_pre.loc[mask_pre, "manual_detected"].mean() * 100,
        df_raw.loc[mask_raw, "manual_detected"].mean() * 100,
        df_pre.loc[mask_pre, "drain_detected"].mean() * 100,
        df_raw.loc[mask_raw, "drain_detected"].mean() * 100
    ]

    bars = ax.bar(range(len(methods)), rates, color=colors, alpha=0.8)
    ax.set_xticks(range(len(methods)))
    ax.set_xticklabels(methods, rotation=45, ha='right', fontsize=10)
    ax.set_ylabel('Detection Rate (%)', fontsize=11)
    ax.set_title(f'{cat}', fontsize=13, fontweight='bold')
    ax.set_ylim([0, 110])
    ax.grid(axis='y', alpha=0.3)

    # Annotazioni
    for bar, rate in zip(bars, rates):
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height + 2,
                f'{rate:.1f}%', ha='center', va='bottom', fontsize=9)

plt.tight_layout()
plt.show()

# Grafico 2: Metrics Comparison (Manual vs Drain)
fig, ax = plt.subplots(figsize=(12, 6))

metrics_names = ['Precision', 'Recall', 'F1-Score']
x = np.arange(len(metrics_names))
width = 0.2

manual_pre = [manual_pre_metrics['precision'], manual_pre_metrics['recall'], manual_pre_metrics['f1']]
manual_raw = [manual_raw_metrics['precision'], manual_raw_metrics['recall'], manual_raw_metrics['f1']]
drain_pre = [drain_pre_metrics['precision'], drain_pre_metrics['recall'], drain_pre_metrics['f1']]
drain_raw = [drain_raw_metrics['precision'], drain_raw_metrics['recall'], drain_raw_metrics['f1']]

ax.bar(x - 1.5*width, manual_pre, width, label='Manual (PREPROC)', color='#1f77b4', alpha=0.9)
ax.bar(x - 0.5*width, manual_raw, width, label='Manual (RAW)', color='#ff7f0e', alpha=0.9)
ax.bar(x + 0.5*width, drain_pre, width, label='Drain (PREPROC)', color='#2ca02c', alpha=0.9)
ax.bar(x + 1.5*width, drain_raw, width, label='Drain (RAW)', color='#d62728', alpha=0.9)

ax.set_xlabel('Metriche', fontsize=13, fontweight='bold')
ax.set_ylabel('Valore', fontsize=13, fontweight='bold')
ax.set_title('Confronto Performance: Manual vs Drain (RAW vs PREPROC)', fontsize=14, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(metrics_names, fontsize=12)
ax.set_ylim([0, 1.1])
ax.legend(fontsize=11, loc='lower right')
ax.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.show()

# Grafico 3: Component Heatmap (F1-score)
components = ['apiserver', 'scheduler', 'controller']
f1_matrix = []

for comp_name in ["kube-apiserver", "kube-scheduler", "kube-controller-manager"]:
    mask_raw = (df_raw["component"] == comp_name) & (df_raw["is_fault_injection"] == True)
    mask_pre = (df_pre["component"] == comp_name) & (df_pre["is_fault_injection"] == True)

    if mask_raw.sum() < 3:
        f1_matrix.append([0, 0, 0, 0])
        continue

    m_r = compute_binary_metrics(df_raw.loc[mask_raw, "is_fault_injection"].astype(int),
                                   df_raw.loc[mask_raw, "manual_detected"].astype(int))
    m_p = compute_binary_metrics(df_pre.loc[mask_pre, "is_fault_injection"].astype(int),
                                   df_pre.loc[mask_pre, "manual_detected"].astype(int))
    d_r = compute_binary_metrics(df_raw.loc[mask_raw, "is_fault_injection"].astype(int),
                                   df_raw.loc[mask_raw, "drain_detected"].astype(int))
    d_p = compute_binary_metrics(df_pre.loc[mask_pre, "is_fault_injection"].astype(int),
                                   df_pre.loc[mask_pre, "drain_detected"].astype(int))

    f1_matrix.append([m_p['f1'], m_r['f1'], d_p['f1'], d_r['f1']])

fig, ax = plt.subplots(figsize=(10, 6))
im = ax.imshow(f1_matrix, cmap='RdYlGn', aspect='auto', vmin=0, vmax=1)

ax.set_xticks(np.arange(4))
ax.set_yticks(np.arange(3))
ax.set_xticklabels(['Manual\n(PREPROC)', 'Manual\n(RAW)', 'Drain\n(PREPROC)', 'Drain\n(RAW)'], fontsize=11)
ax.set_yticklabels(components, fontsize=11)

ax.set_title('F1-Score per Componente (Fault Injection)', fontsize=14, fontweight='bold')

for i in range(3):
    for j in range(4):
        text = ax.text(j, i, f'{f1_matrix[i][j]:.3f}',
                       ha="center", va="center", color="black", fontsize=12, fontweight='bold')

cbar = fig.colorbar(im, ax=ax)
cbar.set_label('F1-Score', rotation=270, labelpad=20, fontsize=12)

plt.tight_layout()
plt.show()

# Grafico 4: Cluster Statistics
fig, ax = plt.subplots(figsize=(10, 6))

categories_cluster = ['Total Clusters', 'Suspicious Clusters']
x = np.arange(len(categories_cluster))
width = 0.35

raw_values = [total_clusters_raw, susp_raw]
pre_values = [total_clusters_pre, susp_pre]

bars1 = ax.bar(x - width/2, raw_values, width, label='RAW', color='#ff7f0e', alpha=0.9)
bars2 = ax.bar(x + width/2, pre_values, width, label='PREPROC', color='#1f77b4', alpha=0.9)

ax.set_xlabel('Tipo Cluster', fontsize=13, fontweight='bold')
ax.set_ylabel('Numero Cluster', fontsize=13, fontweight='bold')
ax.set_title('Generazione Cluster: RAW vs PREPROC', fontsize=14, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(categories_cluster, fontsize=12)
ax.legend(fontsize=12)
ax.grid(axis='y', alpha=0.3)

# Annotazioni
for bar in bars1:
    height = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2., height + 20,
            f'{int(height)}', ha='center', va='bottom', fontsize=11, fontweight='bold')

for bar in bars2:
    height = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2., height + 20,
            f'{int(height)}', ha='center', va='bottom', fontsize=11, fontweight='bold')

plt.tight_layout()
plt.show()

# ===============================================
# SEZIONE 11: TOP CLUSTER SOSPETTI
# ===============================================

print(f"\n{'='*80}")
print("TOP 20 CLUSTER SOSPETTI (PREPROC MODE)")
print(f"{'='*80}")

total_lines_pre = sum(cluster_total_pre.values())
susp_clusters_pre = [(cid, info) for cid, info in clusters_pre.items() if info["is_suspicious"]]
susp_sorted_pre = sorted(susp_clusters_pre, key=lambda x: x[1]["size"], reverse=True)

print(f"\nTotale cluster sospetti: {len(susp_sorted_pre)}")
print(f"Showing top 20:\n")

for i, (cid, info) in enumerate(susp_sorted_pre[:20], 1):
    kw_pct = 100 * info['keyword_count'] / info['size'] if info['size'] > 0 else 0
    size_pct = 100 * info['size'] / total_lines_pre if total_lines_pre > 0 else 0
    print(f"{i:2d}. [CID {cid:3d}] size={info['size']:5d} ({size_pct:4.1f}%), keywords={info['keyword_count']:4d} ({kw_pct:4.1f}%)")
    print(f"    Template: {info['template'][:150]}")

# ===============================================
# SEZIONE 12: ANALISI QUALITATIVA BASELINE
# ===============================================

print(f"\n{'='*80}")
print("ANALISI QUALITATIVA: FILE BASELINE RILEVATI")
print(f"{'='*80}")

baseline_detected = df_pre[(df_pre["category"] == "baseline") & (df_pre["manual_detected"] == True)]

if len(baseline_detected) > 0:
    print(f"\nFile baseline rilevati come anomali: {len(baseline_detected)}/{(df_pre['category']=='baseline').sum()}")
    print("\nTop 10 file baseline con più keyword:")

    top_baseline = baseline_detected.nlargest(10, 'manual_matches')

    for idx, row in top_baseline.iterrows():
        kw_pct = 100 * row['manual_matches'] / row['total_lines'] if row['total_lines'] > 0 else 0
        print(f"\n  File: {os.path.basename(row['file'])}")
        print(f"    Component: {row['component']}")
        print(f"    Keywords: {row['manual_matches']}/{row['total_lines']} ({kw_pct:.2f}%)")
        print(f"    Cluster visti: {row['drain_num_clusters_seen']}")
else:
    print("\nNessun file baseline rilevato come anomalo.")

# ===============================================
# SEZIONE 13: SUMMARY FINALE
# ===============================================

print(f"\n{'='*80}")
print("SUMMARY ESECUZIONE COMPLETA")
print(f"{'='*80}")

print(f"\nDataset:")
print(f"  - File totali analizzati: {len(all_files)}")
print(f"  - Tempo totale esecuzione: {(elapsed_raw + elapsed_pre)/60:.1f} minuti")
print(f"  - Tempo medio per file: {(elapsed_raw + elapsed_pre)/len(all_files)/2:.2f} secondi")

print(f"\nRisultati Chiave:")
print(f"  - Manual (PREPROC): Precision={manual_pre_metrics['precision']:.3f}, Recall={manual_pre_metrics['recall']:.3f}, F1={manual_pre_metrics['f1']:.3f}")
print(f"  - Drain (PREPROC):  Precision={drain_pre_metrics['precision']:.3f}, Recall={drain_pre_metrics['recall']:.3f}, F1={drain_pre_metrics['f1']:.3f}")
print(f"  - Δ Manual vs Drain: Recall={drain_pre_metrics['recall']-manual_pre_metrics['recall']:+.3f}, F1={drain_pre_metrics['f1']-manual_pre_metrics['f1']:+.3f}")

print(f"\nImpatto Preprocessing:")
print(f"  - Manual: Recall {manual_pre_metrics['recall']:.3f} (PREPROC) vs {manual_raw_metrics['recall']:.3f} (RAW) → Δ={manual_raw_metrics['recall']-manual_pre_metrics['recall']:+.3f}")
print(f"  - Drain:  Recall {drain_pre_metrics['recall']:.3f} (PREPROC) vs {drain_raw_metrics['recall']:.3f} (RAW) → Δ={drain_raw_metrics['recall']-drain_pre_metrics['recall']:+.3f}")
print(f"  - Cluster: {total_clusters_pre} (PREPROC) vs {total_clusters_raw} (RAW) → Riduzione {100*(total_clusters_raw-total_clusters_pre)/total_clusters_raw:.1f}%")

print(f"\nTest Statistici:")
print(f"  - McNemar (Manual vs Drain, PREPROC): p={mres.pvalue:.4f}")
print(f"  - Cohen's Kappa (baseline, PREPROC): κ={kappa:.3f}")

print(f"\n{'='*80}")
print("✓ ANALISI COMPLETA")
print(f"{'='*80}\n")

print("\n[INFO] Per salvare i DataFrames in CSV (opzionale):")
print("  df_raw.to_csv('results_raw.csv', index=False)")
print("  df_pre.to_csv('results_preproc.csv', index=False)")